### ISSUE TITLE
last day of month L not supported ,throw error

### ISSUE THREAD

**Issue by mohamedmohsin** [ncb000gt/node-cron#167]

**Comment by aktary** [comment]
Is there *any* way to schedule recurring jobs for the last day of the month??

**Comment by ncb000gt** [comment]
@aktary and @mohamedmohsin There is currently not a way. I've been considering switching over to a different parser to get features like this, but at the moment, no. Because `L` isn't supported in the cron syntax it should throw an exception. I've added a few tests to ensure this is the case. If I do switch over to a different parser then this will be one of the many features I tried to include. :)

**Comment by ncb000gt** [comment]
@aktary the only real way would be to do that within the `onComplete` where you create a new job that fires where you can get and set the last day of the month...it might be a feature I add in at some point if I don't end up using a different parser.

**Comment by haifahrul** [comment]
Maybe you can use the logic here. You can use package momentJS.


```JS
var CronJob = require('cron').CronJob;
var moment = require('moment');

new CronJob('0 00 16 28-31 * *, function() {
  console.log('You will see this message every second');

  if (isLastDayOfMonth()) {
    doSomeStuff()
  }
}, null, true, 'America/Los_Angeles');

function isLastDayOfMonth(){
  const currentDay  =  moment().format('YYYY-MM-DD');
  const lastDayOfCurrentMonth  =  moment(date).endOf('month').format('YYYY-MM-DD');

  if (currentDate === lastDayOfCurrentMonth) {
    return true;
  } else {
    return false;
  }
}

function doSomeStuff(){
  // your task here.
}
```

The cron will be run every 28 - 31 day, and then check whether current day is a last day of current month.
