### ISSUE TITLE
How to remove / overwrite cronjob ?

### ISSUE THREAD

**Issue by dinhquydcn92** [ncb000gt/node-cron#219]
I have cronjob run at 19:30:00 .I want delete it.Can you help me ?

**Comment by klinquist** [comment]
```
///Start job

var CronJob = require('cron').CronJob;
var job = new CronJob(new Date(), function() {
  /* runs once at the specified date. */
  }, function () {
    /* This function is executed when the job stops */
  },
  true, /* Start the job right now */
  timeZone /* Time zone of this job. */
);

///Stop job
job.stop();

**Comment by Kaliph** [comment]
I have the exact same problem. Lets say I have a function like this

 function SetCronJob (date1){ 

`  var job1 = new CronJob(date1, function() {
        console.log("crontest");
    }, function () {
      /* This function is executed when the job stops */
      console.log("job 1 stopped");
    },
     false /* Start the job right now */
    // timeZone /* Time zone of this job. */
  );        
},                                                                               `

**Comment by Connor-Knabe** [comment]
I am curious about this as well.  

I've tried both job.stop() and job = null 
They don't seem to clean it up completely.

**Comment by Kaliph** [comment]
Are u also a beginner in Programming? At the Moment i don't have a Solution. 

Von meinem iPhone gesendet

**Comment by ncb000gt** [comment]
`job.stop()` should clear the timeout and fire the 'finished' callback.

@Connor-Knabe what do you mean "clean it up completely"? Stop isn't intended to clean up the parse syntax or necessarily the other state of the job because you may restart it or set a new time or cron syntax for the job. If you stop and then set the job to null, gc should appropriately clean up the remaining variables. Please let me know if you are seeing otherwise and I can look into that more closely.

**Comment by jevho** [comment]
Currently I'm trying to solve a task, where I need to frequently create one time execution jobs and dispose of them.

**Comment by ncb000gt** [comment]
@jevho gc just cleans up the references. You stopping the job using `job.stop()` would explicitly stop it. Or, you can use a specific date which will run the job once and not execute again. You create the object though, so you hold the reference. Does that help or did I misunderstand your question?

**Comment by jevho** [comment]
Had have to read a little bit more about JavaScript internal mechanics, as I came from C++.
Indeed all one need is to clear the reference in variable, GC manages the rest nicely.
Thanks!

**Comment by jevho** [comment]
Are you sure the job is being removed from memory heap by GC since it loses all references to it?
If you create job and delete reference to it, it still runs:
`
const CronJob = require('cron').CronJob
let a = {}
a.j = new CronJob({cronTime: '*/3 * * * * *', onTick: function() {console.log(new Date())}, start: true})
delete a.j
`
will continue to output dates.
Is it collected from memory if you do `stop()` on it first?

**Comment by jevho** [comment]
Seems it works:
```
$ node --expose-gc
> process.memoryUsage().heapUsed
4870000
> const CronJob = require('cron').CronJob
undefined
> process.memoryUsage().heapUsed
8305768
> let jobs = []
undefined
> const date = new Date('2222-11-20 00:00:00')
undefined
> for (let i = 0; i < 100000; i++ ) {jobs.push(new CronJob({cronTime: date, start: true, onTick: () => {}}))}
100000
> process.memoryUsage().heapUsed
170799072
> jobs.forEach((item, i) => {item.stop(); delete jobs[i]})
undefined
> process.memoryUsage().heapUsed
183761544
> global.gc()
undefined
> process.memoryUsage().heapUsed
7923520
>
```
Thanks for your attention and patience!
