### ISSUE TITLE
Cancel Next/One Occurence

### ISSUE THREAD

**Issue by KyleKing** [ncb000gt/node-cron#253]
I always find that when writing a Github issue, I suddenly find the answer, but I figured I'd post this here and ask if node-cron can already do this or if someone can think of a better way?

My solution is to update a database entry with all of the task ID's that need to be rescheduled. Then at midnight, a repeating cron task would scheduled them and remove the task IDs from the DB entry.

**Comment by ncb000gt** [comment]
Cron doing cron? Pretty meta. :)

So, right now you have the ability to stop a job once it is fired, you do not have the ability to skip jobs outside of the syntax level controls you have.

For instance, if you wanted to have a job run every 5 minutes but skip it when it's 15 then you'd have to do something like: `0 0,5,10,20,25,30,35,40,45,50,55 * * * *` or something along those lines.

Otherwise, I think you're on the right track with managing the scheduling outside. This project doesn't yet aim to be a scheduler. :)
